# Generated by Django 3.2.5 on 2021-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesiuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsuser',
            options={'verbose_name': '게시판사용자', 'verbose_name_plural': '게시판사용자'},
        ),
        migrations.AddField(
            model_name='gsuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
