# Generated by Django 3.2.5 on 2021-07-26 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesiuser', '0002_auto_20210710_0804'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AddField(
            model_name='board',
            name='contents',
            field=models.TextField(default='hi', verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gesiuser.gsuser', verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='board',
            table='gesipan_board',
        ),
    ]
